/**
 * Writes supabase/seed.sql from src/lib/demo/seed.ts so the SQL seed and the
 * in-browser demo never drift apart.   Run:  npm run seed:sql
 *
 * People are not inserted (they come from Supabase Auth). Rows that point at a
 * person look them up by email, so the seed works whether or not the demo
 * accounts exist. Missing people simply become NULL.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { demoSnapshot as s } from "../src/lib/demo/seed";

const q = (v: unknown): string => {
  if (v === undefined || v === null || v === "") return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const emailOf = new Map(s.profiles.map((p) => [p.id, p.email]));
const person = (id?: string) => (id ? `(select id from public.profiles where email = ${q(emailOf.get(id))})` : "null");
const rows = (lines: string[]) => lines.join(",\n");

const out: string[] = [];
out.push(`-- GENERATED by scripts/generate-seed.ts. Do not edit by hand.
-- DEMO DATA. Skip this file for a real deployment (see SUPABASE_SETUP.md, step 16).
begin;
`);

out.push(`update public.society_settings set
  society_name = ${q(s.settings.societyName)},
  subtitle = ${q(s.settings.subtitle)},
  opening_balance = ${s.settings.openingBalance},
  opening_balance_date = ${q(s.settings.openingBalanceDate)},
  receipt_footer = ${q(s.settings.receiptFooter)}
where id = 1;
`);

out.push(`insert into public.categories (id, name, kind, color) values
${rows(s.categories.map((c) => `  (${q(c.id)}, ${q(c.name)}, ${q(c.kind)}, ${q(c.color)})`))}
on conflict do nothing;
`);

out.push(`insert into public.events (id, code, name, type, status, start_date, end_date, days, location, description, target_amount, budget, expected_vendors, default_day_fee, created_by, created_at) values
${rows(
  s.events.map(
    (e) =>
      `  (${q(e.id)}, ${q(e.code)}, ${q(e.name)}, ${q(e.type)}, ${q(e.status)}, ${q(e.startDate)}, ${q(e.endDate)}, ${e.days}, ${q(e.location)}, ${q(e.description)}, ${q(e.targetAmount)}, ${q(e.budget)}, ${q(e.expectedVendors)}, ${q(e.defaultDayFee)}, ${person(e.createdBy)}, ${q(e.createdAt)})`,
  ),
)};
select setval('public.event_code_seq', ${s.events.length});
`);

for (const m of s.eventMembers) {
  out.push(
    `insert into public.event_members (event_id, profile_id, duty) select ${q(m.eventId)}, p.id, ${q(m.duty)} from public.profiles p where p.email = ${q(emailOf.get(m.profileId))} on conflict do nothing;`,
  );
}
out.push("");

out.push(`insert into public.vendors (id, code, business_name, owner_name, phone, stall_type, notes, created_at) values
${rows(s.vendors.map((v) => `  (${q(v.id)}, ${q(v.code)}, ${q(v.businessName)}, ${q(v.ownerName)}, ${q(v.phone)}, ${q(v.stallType)}, ${q(v.notes)}, ${q(v.createdAt)})`))};
select setval('public.vendor_code_seq', ${s.vendors.length});
`);

out.push(`insert into public.event_vendors (id, event_id, vendor_id, stall_no, stall_type, day_fees, notes, created_at) values
${rows(
  s.eventVendors.map(
    (b) =>
      `  (${q(b.id)}, ${q(b.eventId)}, ${q(b.vendorId)}, ${q(b.stallNo)}, ${q(b.stallType)}, '{${b.dayFees.join(",")}}', ${q(b.notes)}, ${q(b.createdAt)})`,
  ),
)};
`);

out.push(`insert into public.transactions (id, code, txn_date, kind, direction, amount, category_id, event_id, method, counterparty, description, reference, status, void_reason, voided_by, voided_at, verified_by, verified_at, created_by, created_at) values
${rows(
  s.transactions.map(
    (t) =>
      `  (${q(t.id)}, ${q(t.code)}, ${q(t.date)}, ${q(t.kind)}, ${q(t.direction)}, ${t.amount}, ${q(t.categoryId)}, ${q(t.eventId)}, ${q(t.method)}, ${q(t.counterparty)}, ${q(t.description)}, ${q(t.reference)}, ${q(t.status)}, ${q(t.voidReason)}, ${person(t.voidedBy)}, ${q(t.voidedAt)}, ${person(t.verifiedBy)}, ${q(t.verifiedAt)}, ${person(t.createdBy)}, ${q(t.createdAt)})`,
  ),
)};
select setval('public.transaction_code_seq', ${s.transactions.length});
`);

out.push(`insert into public.donations (id, transaction_id, donor_name, donor_phone, is_anonymous, purpose, receipt_no) values
${rows(s.donations.map((d) => `  (${q(d.id)}, ${q(d.transactionId)}, ${q(d.donorName)}, ${q(d.donorPhone)}, ${q(d.isAnonymous)}, ${q(d.purpose)}, ${q(d.receiptNo)})`))};
`);

out.push(`insert into public.distributions (id, transaction_id, recipient_name, recipient_type, recipient_contact, beneficiary_count, reference_no) values
${rows(s.distributions.map((d) => `  (${q(d.id)}, ${q(d.transactionId)}, ${q(d.recipientName)}, ${q(d.recipientType)}, ${q(d.recipientContact)}, ${d.beneficiaryCount}, ${q(d.referenceNo)})`))};
`);

out.push(`insert into public.vendor_payments (id, transaction_id, event_vendor_id, receipt_no) values
${rows(s.vendorPayments.map((p) => `  (${q(p.id)}, ${q(p.transactionId)}, ${q(p.eventVendorId)}, ${q(p.receiptNo)})`))};
`);

// Receipt counters continue from the highest seeded number per prefix/year
const counters = new Map<string, number>();
const bump = (no: string) => {
  const [prefix, year, n] = no.split("-");
  const key = `${prefix}-${year}`;
  counters.set(key, Math.max(counters.get(key) ?? 0, Number(n)));
};
s.vendorPayments.forEach((p) => bump(p.receiptNo));
s.donations.forEach((d) => bump(d.receiptNo));
s.distributions.forEach((d) => bump(d.referenceNo));
out.push(`insert into public.doc_counters (prefix, year, last_value) values
${rows([...counters.entries()].map(([k, v]) => `  (${q(k.split("-")[0])}, ${k.split("-")[1]}, ${v})`))}
on conflict (prefix, year) do update set last_value = excluded.last_value;
`);

out.push(`insert into public.audit_logs (actor_id, actor_name, action, entity, entity_id, summary, changes, created_at) values
${rows(
  [...s.auditLogs].reverse().map(
    (a) =>
      `  (${person(a.actorId)}, ${q(a.actorName)}, ${q(a.action)}, ${q(a.entity)}, ${q(a.entityId)}, ${q(a.summary)}, ${a.changes ? q(JSON.stringify(a.changes)) + "::jsonb" : "null"}, ${q(a.createdAt)})`,
  ),
)};

commit;
`);

const path = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(path, out.join("\n"));
console.log(`Wrote ${path}: ${s.transactions.length} transactions, ${s.events.length} events, ${s.vendors.length} vendors.`);
